// <auto-generated />
using System;
using Assignment.Service;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Assignment.Migrations
{
    [DbContext(typeof(PostgresDbContext))]
    partial class PostgresDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Assignment.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateNumber")
                        .HasColumnType("integer");

                    b.Property<int>("CandidateNumber1")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LandlineNumber")
                        .HasColumnType("integer");

                    b.Property<int>("PostalCode")
                        .HasMaxLength(5)
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CandidateNumber1");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Assignment.Models.Candidate", b =>
                {
                    b.Property<int>("CandidateNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CandidateNumber"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NativeLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CandidateNumber");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("Assignment.Models.CandidatesAnalytics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AwardedMarks")
                        .HasColumnType("integer");

                    b.Property<int>("CertificateId")
                        .HasColumnType("integer");

                    b.Property<string>("TopicDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("possibleMarks")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.ToTable("CandidatesAnalytics");
                });

            modelBuilder.Entity("Assignment.Models.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssessmentResultLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssessmentTestCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CandidateScore")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ExaminationDate")
                        .HasColumnType("date");

                    b.Property<int>("MaximumScore")
                        .HasColumnType("integer");

                    b.Property<int>("PercentageScore")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ScoreReportDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("Assignment.Models.Mobile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateNumber")
                        .HasColumnType("integer");

                    b.Property<int>("CandidateNumber1")
                        .HasColumnType("integer");

                    b.Property<int>("MobileNumber")
                        .HasMaxLength(10)
                        .HasColumnType("integer");

                    b.Property<string>("MobileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CandidateNumber1");

                    b.ToTable("Mobiles");
                });

            modelBuilder.Entity("Assignment.Models.Photo_Id", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateNumber")
                        .HasColumnType("integer");

                    b.Property<int>("CandidateNumber1")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DateOfIssue")
                        .HasColumnType("date");

                    b.Property<int>("PhotoIdImage")
                        .HasColumnType("integer");

                    b.Property<int>("photoIdNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidateNumber1");

                    b.ToTable("photo_Ids");
                });

            modelBuilder.Entity("CandidateCertificate", b =>
                {
                    b.Property<int>("CandidatesCandidateNumber")
                        .HasColumnType("integer");

                    b.Property<int>("CertificatesId")
                        .HasColumnType("integer");

                    b.HasKey("CandidatesCandidateNumber", "CertificatesId");

                    b.HasIndex("CertificatesId");

                    b.ToTable("CandidateCertificate");
                });

            modelBuilder.Entity("Assignment.Models.Address", b =>
                {
                    b.HasOne("Assignment.Models.Candidate", "Candidate")
                        .WithMany("Addresses")
                        .HasForeignKey("CandidateNumber1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("Assignment.Models.CandidatesAnalytics", b =>
                {
                    b.HasOne("Assignment.Models.Certificate", "Certificate")
                        .WithMany("CandidatesAnalytics")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("Assignment.Models.Mobile", b =>
                {
                    b.HasOne("Assignment.Models.Candidate", "Candidate")
                        .WithMany("Mobiles")
                        .HasForeignKey("CandidateNumber1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("Assignment.Models.Photo_Id", b =>
                {
                    b.HasOne("Assignment.Models.Candidate", "Candidate")
                        .WithMany("Photo_Id")
                        .HasForeignKey("CandidateNumber1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("CandidateCertificate", b =>
                {
                    b.HasOne("Assignment.Models.Candidate", null)
                        .WithMany()
                        .HasForeignKey("CandidatesCandidateNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment.Models.Certificate", null)
                        .WithMany()
                        .HasForeignKey("CertificatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Assignment.Models.Candidate", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Mobiles");

                    b.Navigation("Photo_Id");
                });

            modelBuilder.Entity("Assignment.Models.Certificate", b =>
                {
                    b.Navigation("CandidatesAnalytics");
                });
#pragma warning restore 612, 618
        }
    }
}
